/** Design reminder — white product onboarding with a green, direct start action. */
import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { AppFrame } from '../components/common/AppFrame'
import { SeniorButton } from '../components/ui/SeniorButton'
import { useAuthStore } from '../store/authStore'
const apiOrigin = new URL(import.meta.env.VITE_API_BASE_URL ?? window.location.origin).origin
const GOOGLE_LOGIN_URL = `${apiOrigin}/oauth2/authorization/google`
export function LoginPage() { const navigate = useNavigate(); const token = useAuthStore((state) => state.token); useEffect(() => { if (token) navigate('/home') }, [token, navigate]); const handleGoogleLogin = () => { window.location.href = GOOGLE_LOGIN_URL }; const handleDevBypass = () => { useAuthStore.getState().setAuth({ token: 'dev-fake-token', userId: 'dev-user', isNewUser: false }) }; return <AppFrame><main className="salad-login flex h-full min-h-0 flex-col bg-white px-6 pb-7 pt-6"><header className="flex items-center gap-2"><span className="salad-login__mark flex h-9 w-9 items-center justify-center"><img src="/manus-storage/cheok-logo-mark_977663d4.png" alt="척척 로고" className="h-5 w-5" /></span><span className="text-[19px] font-bold tracking-[-0.05em] text-[#111]">척척</span></header><section className="my-auto"><div className="salad-login__bubble flex h-[86px] w-[86px] items-center justify-center rounded-full"><span className="text-[32px] font-bold text-[#13bd7e]">+</span></div><p className="mt-7 text-[15px] font-bold text-[#13bd7e]">생활이 더 쉬워지는 시작</p><h1 className="mt-2 text-[34px] font-bold leading-[1.25] tracking-[-0.06em] text-[#111]">필요한 일을<br />쉽고 편하게 해결해요.</h1><p className="mt-4 max-w-[290px] text-[16px] font-medium leading-7 tracking-[-0.03em] text-[#555c68]">길 찾기부터 기차 예매까지, 매일 필요한 도움을 한 곳에서 받아보세요.</p></section><section className="border-t border-[#f0f2f5] pt-5"><SeniorButton type="button" onClick={handleGoogleLogin} leadingIcon={<GoogleMark />}>구글 계정으로 시작하기</SeniorButton>{import.meta.env.DEV ? <SeniorButton type="button" onClick={handleDevBypass} variant="quiet" className="mt-2">바로 둘러보기</SeniorButton> : null}</section></main></AppFrame> }
function GoogleMark() { return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" aria-hidden="true"><path d="M20 12.2c0 4.3-2.9 7.3-7.2 7.3A7.5 7.5 0 1 1 19.9 9H13v3.2h6.8" /></svg> }
