/** Design reminder — route search is a fixed three-stage board: input, verify, launch. */
import { useCallback, useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { routesApi } from '../api/routesApi'
import { AppFrame } from '../components/common/AppFrame'
import { MobileHeader } from '../components/common/MobileHeader'
import { SeniorInput } from '../components/ui/SeniorInput'
import { useTTS } from '../hooks/useTTS'
import { openDeepLinkWithWebFallback } from '../lib/deepLink'
import { resolveMapAutofill } from '../lib/voiceAutofill'
import { useVoiceSessionStore } from '../store/voiceSessionStore'

export function MapRouteScreen() {
  const navigate = useNavigate(); const location = useLocation(); const { speak } = useTTS()
  const voiceSlots = useVoiceSessionStore((state) => state.slots); const voiceData = useVoiceSessionStore((state) => state.data); const voiceTranscript = useVoiceSessionStore((state) => state.transcript)
  const [startName, setStartName] = useState(''); const [goalName, setGoalName] = useState(''); const [startError, setStartError] = useState(''); const [goalError, setGoalError] = useState(''); const [generalError, setGeneralError] = useState(''); const [canRetry, setCanRetry] = useState(false); const [status, setStatus] = useState('idle'); const [voicePrefillNotice, setVoicePrefillNotice] = useState('')
  useEffect(() => { const voiceState = location.state ?? {}; const { startName: spokenStart, goalName: spokenGoal } = resolveMapAutofill({ slots: voiceState.slots ?? voiceSlots, data: voiceState.data ?? voiceData, transcript: voiceState.transcript ?? voiceTranscript }); if (spokenStart) setStartName((current) => current || spokenStart); if (spokenGoal) setGoalName((current) => current || spokenGoal); if (spokenStart || spokenGoal) setVoicePrefillNotice('음성으로 말씀하신 장소를 입력했어요. 내용을 확인해 주세요.') }, [location.state, voiceData, voiceSlots, voiceTranscript])
  const clearErrors = useCallback(() => { setStartError(''); setGoalError(''); setGeneralError(''); setCanRetry(false) }, [])
  const runSearch = useCallback(async () => { const trimmedStart = startName.trim(); const trimmedGoal = goalName.trim(); if (!trimmedStart || !trimmedGoal) { setGeneralError('출발지와 목적지를 모두 입력해주세요.'); return } clearErrors(); setStatus('loading'); try { const { naverMapAppUrl, naverMapWebUrl } = await routesApi.getNaverMapLink({ startName: trimmedStart, goalName: trimmedGoal }); speak(`${trimmedStart}에서 ${trimmedGoal}까지 경로를 네이버 지도에서 열어드릴게요.`); openDeepLinkWithWebFallback(naverMapAppUrl, naverMapWebUrl); setStatus('idle') } catch (error) { const code = error.response?.data?.error?.code; const field = error.response?.data?.error?.field; const message = error.response?.data?.error?.message; if (code === 'GEOCODE_NOT_FOUND') { const text = message ?? '해당 장소를 찾을 수 없어요. 다시 입력해주세요.'; if (field === 'startName') setStartError(text); else if (field === 'goalName') setGoalError(text); else setGeneralError(text); speak(text) } else if (code === 'GEOCODE_API_FAIL' || code === 'EXTERNAL_API_FAIL') { const text = message ?? '경로를 찾는 중 문제가 생겼어요. 다시 시도해주세요.'; setGeneralError(text); setCanRetry(true); speak(text) } else { const text = message ?? '경로를 찾는 데 실패했어요. 다시 시도해주세요.'; setGeneralError(text); setCanRetry(true); speak(text) } setStatus('idle') } }, [startName, goalName, speak, clearErrors])
  const disabled = status === 'loading' || !startName.trim() || !goalName.trim()
  return <AppFrame><main className="control-form-screen flex h-full min-h-0 flex-col overflow-hidden bg-[var(--cb-cream)]"><MobileHeader title="길 찾기" onBack={() => navigate('/home')} /><ProgressStrip current={1} /><form onSubmit={(event) => { event.preventDefault(); runSearch() }} className="flex min-h-0 flex-1 flex-col"><section className="px-5 pb-4 pt-5"><p className="text-[12px] font-extrabold tracking-[0.16em] text-[var(--cb-teal)]">길찾기 조종</p><h1 className="mt-2 text-[30px] font-extrabold leading-[1.06] tracking-[-0.08em]">어디에서 어디로<br />가시나요?</h1></section><section className="control-form-screen__body flex-1 px-5 py-4">{voicePrefillNotice ? <p className="control-notice mb-4">{voicePrefillNotice}</p> : null}<div className="control-number-field"><span>01</span><SeniorInput id="start-name" label="출발지" value={startName} onChange={(event) => setStartName(event.target.value)} placeholder="예: 서울역" error={startError} /></div><div className="control-number-field mt-5"><span>02</span><SeniorInput id="goal-name" label="목적지" value={goalName} onChange={(event) => setGoalName(event.target.value)} placeholder="예: 부산역" error={goalError} /></div></section><footer className="control-form-screen__action shrink-0 px-5 py-4">{generalError ? <p role="alert" className="mb-3 text-[14px] font-bold leading-5 text-[var(--cb-error)]">{generalError}</p> : null}<button type="submit" disabled={disabled} className="control-button control-button--primary flex min-h-14 w-full items-center justify-center gap-3 text-[18px] font-extrabold text-white disabled:opacity-45">{status === 'loading' ? <><span className="h-5 w-5 animate-spin rounded-full border-2 border-white/40 border-t-white" />길을 찾고 있어요</> : '네이버 지도 열기'}</button>{canRetry ? <button type="button" onClick={runSearch} className="control-button control-button--secondary mt-3 min-h-12 w-full text-[16px] font-extrabold">다시 시도</button> : null}</footer></form></main></AppFrame>
}

function ProgressStrip({ current }) { return <div className="control-progress grid grid-cols-3" aria-label="길찾기 진행 단계">{['입력', '확인', '실행'].map((label, index) => <div key={label} className={index + 1 === current ? 'is-current' : ''}><span>0{index + 1}</span><strong>{label}</strong></div>)}</div> }
